# Agent Configuration - Maps agents to their respective tools
# Each agent specializes in a specific domain with appropriate tools

agents:
  kubernetes_agent:
    name: "Kubernetes Infrastructure Agent"
    description: "Manages Kubernetes cluster operations and monitoring"
    tools:
      - get_pod_status
      - get_deployment_status
      - get_cluster_events
      - get_resource_usage
      - get_node_status

  logs_agent:
    name: "Application Logs Agent"
    description: "Handles application log analysis and searching"
    tools:
      - search_logs
      - get_error_logs
      - analyze_log_patterns
      - get_recent_logs
      - count_log_events

  metrics_agent:
    name: "Performance Metrics Agent"
    description: "Provides application performance and resource metrics"
    tools:
      - get_performance_metrics
      - get_error_rates
      - get_resource_metrics
      - get_availability_metrics
      - analyze_trends

  runbooks_agent:
    name: "Operational Runbooks Agent"
    description: "Provides operational procedures and troubleshooting guides"
    tools:
      - search_runbooks
      - get_incident_playbook
      - get_troubleshooting_guide
      - get_escalation_procedures
      - get_common_resolutions

# Global tools available to all agents
global_tools:
  - x-amz-bedrock-agentcore-search  # Universal search tool

# Gateway configuration
gateway:
  uri: "your_agentcore_gateway_url"

